# Form implementation generated from reading ui file 'gui_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 860)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.trang_dang_nhap = QtWidgets.QWidget()
        self.trang_dang_nhap.setObjectName("trang_dang_nhap")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.trang_dang_nhap)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(58, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.trang_dang_nhap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMinimumSize(QtCore.QSize(278, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Edt_tk_dn = QtWidgets.QLineEdit(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edt_tk_dn.sizePolicy().hasHeightForWidth())
        self.Edt_tk_dn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.Edt_tk_dn.setFont(font)
        self.Edt_tk_dn.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.Edt_tk_dn.setObjectName("Edt_tk_dn")
        self.verticalLayout_2.addWidget(self.Edt_tk_dn)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.Edt_mk_dn = QtWidgets.QLineEdit(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edt_mk_dn.sizePolicy().hasHeightForWidth())
        self.Edt_mk_dn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.Edt_mk_dn.setFont(font)
        self.Edt_mk_dn.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.Edt_mk_dn.setFrame(True)
        self.Edt_mk_dn.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Edt_mk_dn.setObjectName("Edt_mk_dn")
        self.verticalLayout_2.addWidget(self.Edt_mk_dn)
        self.cb_mk_dn = QtWidgets.QCheckBox(parent=self.frame)
        self.cb_mk_dn.setObjectName("cb_mk_dn")
        self.verticalLayout_2.addWidget(self.cb_mk_dn)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lb_vt_dn = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_vt_dn.sizePolicy().hasHeightForWidth())
        self.lb_vt_dn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.lb_vt_dn.setFont(font)
        self.lb_vt_dn.setStyleSheet("\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"\n"
"")
        self.lb_vt_dn.setText("")
        self.lb_vt_dn.setObjectName("lb_vt_dn")
        self.verticalLayout_2.addWidget(self.lb_vt_dn)
        self.horizontalLayout_3.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(48, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.frame_6 = QtWidgets.QFrame(parent=self.trang_dang_nhap)
        self.frame_6.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.lb_id_face_dn = QtWidgets.QLabel(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_id_face_dn.sizePolicy().hasHeightForWidth())
        self.lb_id_face_dn.setSizePolicy(sizePolicy)
        self.lb_id_face_dn.setStyleSheet("\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"\n"
"")
        self.lb_id_face_dn.setText("")
        self.lb_id_face_dn.setObjectName("lb_id_face_dn")
        self.verticalLayout_6.addWidget(self.lb_id_face_dn)
        self.lb_cam_dn = QtWidgets.QLabel(parent=self.frame_6)
        self.lb_cam_dn.setMinimumSize(QtCore.QSize(300, 300))
        self.lb_cam_dn.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_cam_dn.setFont(font)
        self.lb_cam_dn.setStyleSheet("border: 2px solid black;")
        self.lb_cam_dn.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.lb_cam_dn.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lb_cam_dn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_cam_dn.setObjectName("lb_cam_dn")
        self.verticalLayout_6.addWidget(self.lb_cam_dn)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.trang_dang_nhap)
        self.frame_2.setMinimumSize(QtCore.QSize(400, 140))
        self.frame_2.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_quen_mk_dn = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_quen_mk_dn.setMaximumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_quen_mk_dn.setFont(font)
        self.btn_quen_mk_dn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_quen_mk_dn.setObjectName("btn_quen_mk_dn")
        self.horizontalLayout.addWidget(self.btn_quen_mk_dn)
        self.btn_doi_mk_dn = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_doi_mk_dn.setMaximumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_doi_mk_dn.setFont(font)
        self.btn_doi_mk_dn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_doi_mk_dn.setObjectName("btn_doi_mk_dn")
        self.horizontalLayout.addWidget(self.btn_doi_mk_dn)
        self.btn_face_dn = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_face_dn.sizePolicy().hasHeightForWidth())
        self.btn_face_dn.setSizePolicy(sizePolicy)
        self.btn_face_dn.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_face_dn.setFont(font)
        self.btn_face_dn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 90, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: green;\n"
"}\n"
"")
        self.btn_face_dn.setObjectName("btn_face_dn")
        self.horizontalLayout.addWidget(self.btn_face_dn)
        self.btn_xn_dn = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_xn_dn.sizePolicy().hasHeightForWidth())
        self.btn_xn_dn.setSizePolicy(sizePolicy)
        self.btn_xn_dn.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_xn_dn.setFont(font)
        self.btn_xn_dn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 90, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: green;\n"
"}\n"
"")
        self.btn_xn_dn.setObjectName("btn_xn_dn")
        self.horizontalLayout.addWidget(self.btn_xn_dn)
        self.btn_dk_dn = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dk_dn.sizePolicy().hasHeightForWidth())
        self.btn_dk_dn.setSizePolicy(sizePolicy)
        self.btn_dk_dn.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_dk_dn.setFont(font)
        self.btn_dk_dn.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(40, 26, 227);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_dk_dn.setObjectName("btn_dk_dn")
        self.horizontalLayout.addWidget(self.btn_dk_dn)
        self.verticalLayout_7.addWidget(self.frame_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(58, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.trang_dang_nhap)
        self.trang_doi_mk = QtWidgets.QWidget()
        self.trang_doi_mk.setObjectName("trang_doi_mk")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.trang_doi_mk)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem5 = QtWidgets.QSpacerItem(128, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem6 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_8 = QtWidgets.QFrame(parent=self.trang_doi_mk)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(300, 350))
        self.frame_8.setMaximumSize(QtCore.QSize(300, 450))
        self.frame_8.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_15.addWidget(self.label_16)
        self.edt_tk_doi_mk = QtWidgets.QLineEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_tk_doi_mk.sizePolicy().hasHeightForWidth())
        self.edt_tk_doi_mk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.edt_tk_doi_mk.setFont(font)
        self.edt_tk_doi_mk.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_tk_doi_mk.setObjectName("edt_tk_doi_mk")
        self.verticalLayout_15.addWidget(self.edt_tk_doi_mk)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_15.addWidget(self.label_17)
        self.edt_mkcu = QtWidgets.QLineEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_mkcu.sizePolicy().hasHeightForWidth())
        self.edt_mkcu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.edt_mkcu.setFont(font)
        self.edt_mkcu.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_mkcu.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.edt_mkcu.setObjectName("edt_mkcu")
        self.verticalLayout_15.addWidget(self.edt_mkcu)
        self.cb_mk_cu = QtWidgets.QCheckBox(parent=self.frame_8)
        self.cb_mk_cu.setObjectName("cb_mk_cu")
        self.verticalLayout_15.addWidget(self.cb_mk_cu)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_15.addWidget(self.label_18)
        self.edt_mk_moi = QtWidgets.QLineEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_mk_moi.sizePolicy().hasHeightForWidth())
        self.edt_mk_moi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.edt_mk_moi.setFont(font)
        self.edt_mk_moi.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_mk_moi.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.edt_mk_moi.setObjectName("edt_mk_moi")
        self.verticalLayout_15.addWidget(self.edt_mk_moi)
        self.cb_mkmoi = QtWidgets.QCheckBox(parent=self.frame_8)
        self.cb_mkmoi.setObjectName("cb_mkmoi")
        self.verticalLayout_15.addWidget(self.cb_mkmoi)
        self.label_19 = QtWidgets.QLabel(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_15.addWidget(self.label_19)
        self.edt_xn_mkmoi = QtWidgets.QLineEdit(parent=self.frame_8)
        self.edt_xn_mkmoi.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_xn_mkmoi.setObjectName("edt_xn_mkmoi")
        self.verticalLayout_15.addWidget(self.edt_xn_mkmoi)
        self.cb_xnmk_moi = QtWidgets.QCheckBox(parent=self.frame_8)
        self.cb_xnmk_moi.setObjectName("cb_xnmk_moi")
        self.verticalLayout_15.addWidget(self.cb_xnmk_moi)
        self.horizontalLayout_12.addWidget(self.frame_8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.frame_11 = QtWidgets.QFrame(parent=self.trang_doi_mk)
        self.frame_11.setMinimumSize(QtCore.QSize(633, 108))
        self.frame_11.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_xn_doi_mk = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_xn_doi_mk.sizePolicy().hasHeightForWidth())
        self.btn_xn_doi_mk.setSizePolicy(sizePolicy)
        self.btn_xn_doi_mk.setMaximumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_xn_doi_mk.setFont(font)
        self.btn_xn_doi_mk.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 90, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: green;\n"
"}\n"
"")
        self.btn_xn_doi_mk.setObjectName("btn_xn_doi_mk")
        self.horizontalLayout_13.addWidget(self.btn_xn_doi_mk)
        self.btn_ql_dn_doimk = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ql_dn_doimk.sizePolicy().hasHeightForWidth())
        self.btn_ql_dn_doimk.setSizePolicy(sizePolicy)
        self.btn_ql_dn_doimk.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_ql_dn_doimk.setFont(font)
        self.btn_ql_dn_doimk.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_ql_dn_doimk.setObjectName("btn_ql_dn_doimk")
        self.horizontalLayout_13.addWidget(self.btn_ql_dn_doimk)
        self.verticalLayout_14.addWidget(self.frame_11)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        spacerItem7 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        spacerItem8 = QtWidgets.QSpacerItem(128, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.trang_doi_mk)
        self.trang_dang_ky = QtWidgets.QWidget()
        self.trang_dang_ky.setObjectName("trang_dang_ky")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.trang_dang_ky)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(128, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.trang_dang_ky)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 350))
        self.frame_3.setMaximumSize(QtCore.QSize(300, 450))
        self.frame_3.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.edt_tk_dk = QtWidgets.QLineEdit(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_tk_dk.sizePolicy().hasHeightForWidth())
        self.edt_tk_dk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.edt_tk_dk.setFont(font)
        self.edt_tk_dk.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_tk_dk.setObjectName("edt_tk_dk")
        self.verticalLayout.addWidget(self.edt_tk_dk)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.edt_mk_dk = QtWidgets.QLineEdit(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_mk_dk.sizePolicy().hasHeightForWidth())
        self.edt_mk_dk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.edt_mk_dk.setFont(font)
        self.edt_mk_dk.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_mk_dk.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.edt_mk_dk.setObjectName("edt_mk_dk")
        self.verticalLayout.addWidget(self.edt_mk_dk)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.frame_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.edt_mkl_dk = QtWidgets.QLineEdit(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_mkl_dk.sizePolicy().hasHeightForWidth())
        self.edt_mkl_dk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.edt_mkl_dk.setFont(font)
        self.edt_mkl_dk.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_mkl_dk.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.edt_mkl_dk.setObjectName("edt_mkl_dk")
        self.verticalLayout.addWidget(self.edt_mkl_dk)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.frame_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.lb_vt_dki = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_vt_dki.sizePolicy().hasHeightForWidth())
        self.lb_vt_dki.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.lb_vt_dki.setFont(font)
        self.lb_vt_dki.setStyleSheet("\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"\n"
"")
        self.lb_vt_dki.setText("")
        self.lb_vt_dki.setObjectName("lb_vt_dki")
        self.verticalLayout.addWidget(self.lb_vt_dki)
        self.horizontalLayout_2.addWidget(self.frame_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.frame_5 = QtWidgets.QFrame(parent=self.trang_dang_ky)
        self.frame_5.setMinimumSize(QtCore.QSize(320, 350))
        self.frame_5.setMaximumSize(QtCore.QSize(300, 450))
        self.frame_5.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lb_id_face_dki = QtWidgets.QLabel(parent=self.frame_5)
        self.lb_id_face_dki.setStyleSheet("\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"\n"
"")
        self.lb_id_face_dki.setText("")
        self.lb_id_face_dki.setObjectName("lb_id_face_dki")
        self.verticalLayout_3.addWidget(self.lb_id_face_dki)
        self.lb_cam_dki = QtWidgets.QLabel(parent=self.frame_5)
        self.lb_cam_dki.setMinimumSize(QtCore.QSize(300, 300))
        self.lb_cam_dki.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_cam_dki.setFont(font)
        self.lb_cam_dki.setStyleSheet("border: 2px solid black;")
        self.lb_cam_dki.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.lb_cam_dki.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lb_cam_dki.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_cam_dki.setObjectName("lb_cam_dki")
        self.verticalLayout_3.addWidget(self.lb_cam_dki)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.trang_dang_ky)
        self.frame_4.setMinimumSize(QtCore.QSize(633, 108))
        self.frame_4.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_vt_dki = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_vt_dki.sizePolicy().hasHeightForWidth())
        self.btn_vt_dki.setSizePolicy(sizePolicy)
        self.btn_vt_dki.setMaximumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_vt_dki.setFont(font)
        self.btn_vt_dki.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_vt_dki.setObjectName("btn_vt_dki")
        self.horizontalLayout_4.addWidget(self.btn_vt_dki)
        self.btn_face_dk = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_face_dk.sizePolicy().hasHeightForWidth())
        self.btn_face_dk.setSizePolicy(sizePolicy)
        self.btn_face_dk.setMaximumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_face_dk.setFont(font)
        self.btn_face_dk.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_face_dk.setObjectName("btn_face_dk")
        self.horizontalLayout_4.addWidget(self.btn_face_dk)
        self.btn_xn_dk = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_xn_dk.sizePolicy().hasHeightForWidth())
        self.btn_xn_dk.setSizePolicy(sizePolicy)
        self.btn_xn_dk.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_xn_dk.setFont(font)
        self.btn_xn_dk.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 90, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: green;\n"
"}\n"
"")
        self.btn_xn_dk.setObjectName("btn_xn_dk")
        self.horizontalLayout_4.addWidget(self.btn_xn_dk)
        self.btn_ql_dn = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ql_dn.sizePolicy().hasHeightForWidth())
        self.btn_ql_dn.setSizePolicy(sizePolicy)
        self.btn_ql_dn.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_ql_dn.setFont(font)
        self.btn_ql_dn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_ql_dn.setObjectName("btn_ql_dn")
        self.horizontalLayout_4.addWidget(self.btn_ql_dn)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(128, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.trang_dang_ky)
        self.trang_chinh = QtWidgets.QWidget()
        self.trang_chinh.setObjectName("trang_chinh")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.trang_chinh)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem14 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 0, 0, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem15 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_17.addItem(spacerItem15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_dx_user = QtWidgets.QPushButton(parent=self.trang_chinh)
        self.btn_dx_user.setMinimumSize(QtCore.QSize(110, 50))
        self.btn_dx_user.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_dx_user.setFont(font)
        self.btn_dx_user.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 90, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: green;\n"
"}\n"
"")
        self.btn_dx_user.setObjectName("btn_dx_user")
        self.horizontalLayout_14.addWidget(self.btn_dx_user)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.label_12 = QtWidgets.QLabel(parent=self.trang_chinh)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.lb_tk_dn = QtWidgets.QLabel(parent=self.trang_chinh)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tk_dn.setFont(font)
        self.lb_tk_dn.setObjectName("lb_tk_dn")
        self.horizontalLayout_14.addWidget(self.lb_tk_dn)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fram_thiet_bi = QtWidgets.QFrame(parent=self.trang_chinh)
        self.fram_thiet_bi.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fram_thiet_bi.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fram_thiet_bi.setObjectName("fram_thiet_bi")
        self.verticalLayout_10.addWidget(self.fram_thiet_bi)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lb_tk_tt_2 = QtWidgets.QLabel(parent=self.trang_chinh)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tk_tt_2.setFont(font)
        self.lb_tk_tt_2.setStyleSheet("background-color: rgb(255, 69, 112);\n"
"border: 2px solid black;\n"
"")
        self.lb_tk_tt_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_tk_tt_2.setObjectName("lb_tk_tt_2")
        self.verticalLayout_8.addWidget(self.lb_tk_tt_2)
        self.tableView = QtWidgets.QTableView(parent=self.trang_chinh)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet("border: 2px solid pink;")
        self.tableView.setObjectName("tableView")
        self.verticalLayout_8.addWidget(self.tableView)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lb_tk_tt_3 = QtWidgets.QLabel(parent=self.trang_chinh)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tk_tt_3.setFont(font)
        self.lb_tk_tt_3.setStyleSheet("background-color: rgb(180, 227, 25);\n"
"border: 2px solid black;\n"
"")
        self.lb_tk_tt_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_tk_tt_3.setObjectName("lb_tk_tt_3")
        self.verticalLayout_9.addWidget(self.lb_tk_tt_3)
        self.tableView_2 = QtWidgets.QTableView(parent=self.trang_chinh)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableView_2.setFont(font)
        self.tableView_2.setStyleSheet("border: 2px solid green;")
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_9.addWidget(self.tableView_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.verticalLayout_16.addLayout(self.verticalLayout_10)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        spacerItem18 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem18)
        self.gridLayout_7.addLayout(self.verticalLayout_17, 0, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem19, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.trang_chinh)
        self.trang_quen_mk = QtWidgets.QWidget()
        self.trang_quen_mk.setObjectName("trang_quen_mk")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.trang_quen_mk)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem20 = QtWidgets.QSpacerItem(58, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem21)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_7 = QtWidgets.QFrame(parent=self.trang_quen_mk)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_13.setMinimumSize(QtCore.QSize(278, 50))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.edt_tk_quenmk = QtWidgets.QLineEdit(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_tk_quenmk.sizePolicy().hasHeightForWidth())
        self.edt_tk_quenmk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.edt_tk_quenmk.setFont(font)
        self.edt_tk_quenmk.setStyleSheet("QLineEdit {\n"
"                border: 2px solid black;\n"
"                border-radius: 10px;\n"
"                padding: 10px;\n"
"                background-color: #f5f5f5;\n"
"                color: #333;\n"
"                font-family: Arial, sans-serif;\n"
"                font-size: 14px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 2px solid black;\n"
"            }")
        self.edt_tk_quenmk.setObjectName("edt_tk_quenmk")
        self.verticalLayout_12.addWidget(self.edt_tk_quenmk)
        self.horizontalLayout_9.addWidget(self.frame_7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.frame_9 = QtWidgets.QFrame(parent=self.trang_quen_mk)
        self.frame_9.setMinimumSize(QtCore.QSize(400, 140))
        self.frame_9.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_dn_quen = QtWidgets.QPushButton(parent=self.frame_9)
        self.btn_dn_quen.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_dn_quen.setFont(font)
        self.btn_dn_quen.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    \n"
"    \n"
"}\n"
"")
        self.btn_dn_quen.setObjectName("btn_dn_quen")
        self.horizontalLayout_10.addWidget(self.btn_dn_quen)
        self.btn_xn_clmk = QtWidgets.QPushButton(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_xn_clmk.sizePolicy().hasHeightForWidth())
        self.btn_xn_clmk.setSizePolicy(sizePolicy)
        self.btn_xn_clmk.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_xn_clmk.setFont(font)
        self.btn_xn_clmk.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 90, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: green;\n"
"}\n"
"")
        self.btn_xn_clmk.setObjectName("btn_xn_clmk")
        self.horizontalLayout_10.addWidget(self.btn_xn_clmk)
        self.verticalLayout_11.addWidget(self.frame_9)
        spacerItem22 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem22)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        spacerItem23 = QtWidgets.QSpacerItem(58, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.trang_quen_mk)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đăng nhập"))
        self.label_2.setText(_translate("MainWindow", "Tài khoản (email)"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu"))
        self.cb_mk_dn.setText(_translate("MainWindow", "Hiện mật khẩu"))
        self.label_4.setText(_translate("MainWindow", "Vân tay"))
        self.label_11.setText(_translate("MainWindow", "Khuôn mặt"))
        self.lb_cam_dn.setText(_translate("MainWindow", "Camera Face ID"))
        self.btn_quen_mk_dn.setText(_translate("MainWindow", "Quên mật khẩu"))
        self.btn_doi_mk_dn.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.btn_face_dn.setText(_translate("MainWindow", "FACE ID"))
        self.btn_xn_dn.setText(_translate("MainWindow", "Xác nhận"))
        self.btn_dk_dn.setText(_translate("MainWindow", "Đăng ký"))
        self.label_15.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.label_16.setText(_translate("MainWindow", "Tài khoản"))
        self.label_17.setText(_translate("MainWindow", "Mật khẩu cũ"))
        self.cb_mk_cu.setText(_translate("MainWindow", "Hiện mật khẩu"))
        self.label_18.setText(_translate("MainWindow", "Mật khẩu mới"))
        self.cb_mkmoi.setText(_translate("MainWindow", "Hiện mật khẩu mới"))
        self.label_19.setText(_translate("MainWindow", "Xác nhận mật khẩu mới"))
        self.cb_xnmk_moi.setText(_translate("MainWindow", "Hiện mật khẩu mới xác nhận"))
        self.btn_xn_doi_mk.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.btn_ql_dn_doimk.setText(_translate("MainWindow", "Đăng nhập"))
        self.label_6.setText(_translate("MainWindow", "Đăng ký"))
        self.label_7.setText(_translate("MainWindow", "Tài khoản"))
        self.label_8.setText(_translate("MainWindow", "Mật khẩu"))
        self.checkBox_2.setText(_translate("MainWindow", "Hiện mật khẩu"))
        self.label_10.setText(_translate("MainWindow", "Xác nhận mật khẩu"))
        self.checkBox_3.setText(_translate("MainWindow", "Hiện mật khẩu xác nhận"))
        self.label_9.setText(_translate("MainWindow", "Vân tay"))
        self.label_5.setText(_translate("MainWindow", "Khuôn mặt"))
        self.lb_cam_dki.setText(_translate("MainWindow", "Camera Face ID"))
        self.btn_vt_dki.setText(_translate("MainWindow", "Thêm vân tay"))
        self.btn_face_dk.setText(_translate("MainWindow", "Thêm Face ID"))
        self.btn_xn_dk.setText(_translate("MainWindow", "Xác nhận"))
        self.btn_ql_dn.setText(_translate("MainWindow", "Đăng nhập"))
        self.btn_dx_user.setText(_translate("MainWindow", "Đăng xuất"))
        self.label_12.setText(_translate("MainWindow", "Máy giặt, máy sấy"))
        self.lb_tk_dn.setText(_translate("MainWindow", "Tài khoản"))
        self.lb_tk_tt_2.setText(_translate("MainWindow", "Thông tin hoạt động hệ thống"))
        self.lb_tk_tt_3.setText(_translate("MainWindow", "Thông tin đặt lịch của bạn"))
        self.label_13.setText(_translate("MainWindow", "Quên mật khẩu"))
        self.label_14.setText(_translate("MainWindow", "Tài khoản (email)"))
        self.btn_dn_quen.setText(_translate("MainWindow", "Đăng nhập"))
        self.btn_xn_clmk.setText(_translate("MainWindow", "Cấp lại mật khẩu"))
